### PR TITLE
updated placeholder img

### LINKED ISSUE #324: Update placeholder image
## User story
Guides and stories will always have an image, but we want to be able to save them without so that we can source image separately to text. Therefore, it's best we have a placeholder.

## Acceptance criteria

- [x] If a story or a guide does not have an image, the placeholder shows
- [x] A story and guide can be saved without an image
- [x] The new image is used as default og:image 

## Implementation notes & questions
Autumn is providing an image.

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Fixes #324 

## Description

- all placeholder images replaced with provided file
- meta image resized and cropped to correct dimensions

@geeksforsocialchange/developers

### CODE REVIEW

**Review by ivan-kocienski-gfsc — APPROVED** [review]
LGTM

**Comment by katjam** [comment]
I think we should ask Autumn what the default meta image should be - because the seedling is more of a "image coming soon" vibe. I think the meta default we had before says "community nature" better. Probably my miscommunication.

**Comment by katjam** [comment]
Autumn has supplied large logo for meta. Do you want to swap it in before we merge this?

**Comment by aaaaargZombies** [comment]
I've added the new image

**Pull request merged**
