### PR TITLE
Guide video description CMS field

### LINKED ISSUE #459: Add video description to guide CMS
## User story

As an admin I want to be able to add a (optional) video description to guide videos

## Acceptance criteria

- [ ] guides have video desciption field in CMS
- [ ] can be filled by admin
- [ ] will show up on Guide page
- [ ] can be removed by admin

## Implementation notes & questions

Should just be an edit in the CMS

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes #459

@geeksforsocialchange/developers

### CODE REVIEW

**Review by aaaaargZombies — CHANGES_REQUESTED** [review]
image

I'm assuming this isn't Autumns copy, can we add [cCc] to this or remove.

Otherwise works well.

**Comment by ivan-kocienski-gfsc** [comment]
i didn't think we were doing `[cCc]` in the CMS as it is not public facing?

**Comment by ivan-kocienski-gfsc** [comment]
Ah I got you- i added `[cCc]` to the sample description

**Review by aaaaargZombies — APPROVED** [review]
cheeeeers, I notice a failing build maybe check it's a hicup before merging, can't see why altering the copy would effect it

**Pull request merged**
