### PR TITLE
add elm-review and rules from template

### LINKED ISSUE #21: Set up elm-review
## Description
Set up elm-review to run on build?

## Plan
- [ ]

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Fixes #21

## Description

- add elm-review and rules
- update readme

@geeksforsocialchange/developers

### CODE REVIEW

**Comment by ivan-kocienski-gfsc** [comment]
I think this might be useful to enforce a code-style early on. Something more involved than plain elm-format

**Comment by katjam** [comment]
Are there any files we need to gitignore?

**Comment by r-ferrier** [comment]
> Are there any files we need to gitignore?

I'd like to add `.vscode/* ` to the list as a precaution for any settings I change for this project

**Comment by r-ferrier** [comment]
> > Are there any files we need to gitignore?
> 
> I'd like to add `.vscode/* ` to the list as a precaution for any settings I change for this project

Sorry just realised this is a completely separate issue! I can just do this on my next ticket :)

**Pull request closed without merging**
