### PR TITLE
Update hyperlink appearance

### LINKED ISSUE #463: [Bug]: fix link appearance
## Acceptance criteria

- [ ] All links or link-like buttons are underlined with underline colour at ~50%
- [ ] All links underline goes to 100% colour on hover

### PR DESCRIPTION
**Pull request by r-ferrier**
Fixes #463

## Description

- Adds an underline to all hyperlinks with a 50% shade of text colour
- Underline is boosted to 100% colour on hover
- Underline is not added to any links within headers
- Underline is added to language toggle button

@geeksforsocialchange/developers

### CODE REVIEW

**Review by aaaaargZombies — CHANGES_REQUESTED** [review]
image

missing a button here

Not sure if this would be better with border bottom a bit thicker, example in this content menu thing here https://transsafety.network/posts/toxic-debate-but-good-news/

The underline vs border is not blocking for me. Would happily merge when the buttons fixed.

**Comment by r-ferrier** [comment]
> image
> 
> missing a button here
> 
> Not sure if this would be better with border bottom a bit thicker, example in this content menu thing here https://transsafety.network/posts/toxic-debate-but-good-news/
> 
> The underline vs border is not blocking for me. Would happily merge when the buttons fixed.

Ah! Changing.

I did try a thicker line but couldn't decide if it was preferable or not. Maybe @undividual has a preference on this? Here's some screengrabs for comparison:

Screenshot 2023-06-20 at 13 38 52

Screenshot 2023-06-20 at 13 38 44

**Comment by undividual** [comment]
I prefer the second (subtler) one!

**Review by aaaaargZombies — APPROVED** [review]
Bon!

**Pull request merged**
